### ISSUE TITLE
Embeded Configurator blank screen

### ISSUE THREAD

**Issue by meichthys** [danielperna84/hass-configurator#142]
I've never been able to get the embedded configurator to work using the default configuration.yaml settings:

```
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://<home_assistant_ip>:3218
```

Does anyone else have this setup? 

I'm running Hassio in HassOS in a HyperV vm in case that has anything to do with it.
