### ISSUE TITLE
Configurator in HA, Rapsbian install

### ISSUE THREAD

**Issue by JPFrancoia** [danielperna84/hass-configurator#175]
Hi,

Thanks for developing this add-on.

I installed HA on Raspbian in a virtualenv, everything works, I can access it on my local network at 192.168.0.106:8123.
I then installed configurator in the same virtualenv. Both apps are started with services through systemd. I can access the configurator at 192.168.0.106:3218.

But I can't get the configurator to integrate in HA's front end. As mentioned in the README, I tried to put this snippet in `configuration.yaml`:

```yaml
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.0.106:3218
```

I restarted HA, Configurator is present on the side panel, but when I click on it, I don't seem to get a connection. In the frame, my browser tells me it can't access this address.

After reading a few forum threads, I tried this snippet:

```yaml
panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: hass:settings
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
```

And I also tried different values for `js_url`, including 192.168.0.106:3218. But no luck there either, it seems the connection can't be established.

Could you please give me a hand here?
