### ISSUE TITLE
[0.3.8] Resources missing from docker image

### ISSUE THREAD

**Issue by manutenfruits** [danielperna84/hass-configurator#194]
I recently updated my docker-compose file to use the latest and I experienced some issues where local resources are not loading. The issues seems to have been introduced in 0.3.8 (0.3.7 works fine).

What I observe in chrome devtools is that assets like `jquery-3.4.1.min.js` or `style.css` come empty. They return a 200 but still come empty. Assets from CDN load fine, it's just with local assets. The main html also loads fine.

Here's my config just in case, but nothing unusual:

```
  hass_config:
    container_name: hass_config
    image: danielperna84/hass-configurator:release-0.3.8
    restart: always
    ports:
      - "3218:3218"
    environment:
      - HC_ENFORCE_BASEPATH=True
      - PUID=1000
      - PGID=1000
    volumes:
      - ${MOUNT_POINT}/home-assistant:/config
```
