### ISSUE TITLE
Login error when API token set using env variables in docker compose

### ISSUE THREAD

**Issue by gimeno** [danielperna84/hass-configurator#210]
Version: 0.4.0
I've installed HA and HASS Configurator as docker containers.

If I set `HASS_API_PASSWORD` in the docker compose file I get the below notification in HA each time I load the configurator
_Login attempt or request with invalid authentication from 127.0.0.1_

Only If I set the variable in the `settings.conf` it works fine and the notification doesn't show up

This is the docker-compose setup I've tried and fails
```
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Madrid
    restart: unless-stopped

  ha-configurator:
    container_name: ha-configurator
    image: causticlab/hass-configurator-docker:0.4.0-arm
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./configurator/config:/config
      - ./config:/hass-config
    environment:
      - HASS_API_PASSWORD=MY_TOKEN
```
