### ISSUE TITLE
... space filler makes it difficult to see -

### ISSUE THREAD

**Issue by foxsam21** [danielperna84/hass-configurator#70]
This is really a problem coming from the ace editor. The dots used to fill the spaces makes it difficult to see the all-important - in the yaml config files. The lines that start with a "  - " can easily be missed that they have or are missing it.
For now I just disabled "show invisibles".

**Comment by danielperna84** [comment]
That's not really an issue. As you point out, that's how the Ace Editor displays whitespace, which is useful to keep the syntax correct.
I guess there would be the possibility to add an option to manually set the color / transparency of whitespace. The default is:
```css
.ace-tm .ace_invisible {
	color: rgb(191, 191, 191);
}
```
If we change that to:
```css
.ace-tm .ace_invisible {
	color: rgba(191, 191, 191, 0.3);
}
```
the dots whould be less dominant. But that makes all other whitespace characters less visible as well. So doing this with a customizable option would be the way I would accept, leaving the default as it currently is.
